function ext1a(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 13-Mar-2021 16:41:14

% Import the file
newData1 = load(fileToRead1, '-mat');

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
tic;
[mean_array, covariance, correlation] = estFor(newData1.X)
toc;
tic;
[mean_array, covariance, correlation] = estVec(newData1.X)
toc;
end


function [mean_array, covariance, correlation] = estFor(X)
mean_array = double.empty(0, height(X));
covariance = zeros(height(X), height(X));
correlation = zeros(height(X), height(X));
for i = 1: height(X)
    mean_array(i) = mean(X(i,:));
    for j = 1: height(X)
        cov_i_j = cov(X(i,:), X(j,:));
        corr_i_j = corrcoef(X(i,:), X(j,:));
        covariance(i,j) = cov_i_j(1,2);
        covariance(j,i) = cov_i_j(2,1);
        correlation(i,j) = corr_i_j(1,2);
        correlation(j,i) = corr_i_j(2,1);
    end
end

end


function [mean_array, covariance, correlation] = estVec(X)
mean_array = mean(X, 2);
covariance = cov(transpose(X));
correlation = corrcoef(transpose(X));
end
